export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  DEVICE_NOT_FOUND: "DEVICE_NOT_FOUND",
  ORDER_NOT_FOUND: "ORDER_NOT_FOUND",
  TASK_NOT_FOUND: "TASK_NOT_FOUND",
  ORDER_STATE_INVALID: "ORDER_STATE_INVALID",
  DEVICE_STATE_INVALID: "DEVICE_STATE_INVALID",
  CHECK_ABNORMAL: "CHECK_ABNORMAL",
  HAZARD_UNFINISHED: "HAZARD_UNFINISHED"
} as const;
