ERROR_CODES = {
  "AUTH_REQUIRED": "AUTH_REQUIRED",
  "RBAC_DENIED": "RBAC_DENIED",
  "VALIDATION_FAILED": "VALIDATION_FAILED",
  "INTERNAL_ERROR": "INTERNAL_ERROR",
  "DEVICE_NOT_FOUND": "DEVICE_NOT_FOUND",
  "DEVICE_BUSY": "DEVICE_BUSY",
  "OUTAGE_NOT_FOUND": "OUTAGE_NOT_FOUND",
  "OUTAGE_STATE_INVALID": "OUTAGE_STATE_INVALID",
  "OUTAGE_CHECK_REQUIRED": "OUTAGE_CHECK_REQUIRED",
  "HAZARD_OPEN": "HAZARD_OPEN"
}
