def create_device_status_order_dto(row, device_code: str | None = None) -> dict:
    return {
        "id": row.id,
        "device_id": row.device_id,
        "device_code": device_code,
        "state": row.state,
        "reason": row.reason,
        "expected_recover_at": row.expected_recover_at,
        "applicant_id": row.applicant_id,
        "applicant_name": row.applicant_name,
        "applied_at": row.applied_at,
        "confirmer_id": row.confirmer_id,
        "confirmer_name": row.confirmer_name,
        "confirmed_at": row.confirmed_at,
        "reject_reason": row.reject_reason,
        "checker_id": row.checker_id,
        "checker_name": row.checker_name,
        "checked_at": row.checked_at,
        "check_result": row.check_result,
        "check_note": row.check_note,
        "reactivator_id": row.reactivator_id,
        "reactivator_name": row.reactivator_name,
        "reactivated_at": row.reactivated_at,
        "status_before": row.status_before,
        "status_after": row.status_after,
    }
